server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON


logging:
    config: classpath:log4j2-dev.xml

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true

jwt:
  secret: ffjaksdfjaklf # 生产环境最好以启动参数写入
  expiration: 3600000 # ms 3600s 3600000
  header: JWTHeaderName